### PR TITLE
create database entity for TrayCollects

### PR DESCRIPTION
**Pull request by ZD1wang**
# Description
create tray_collect api, model and test

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
-  test created in test_main.py file
-  manual api testing through postman

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I will rebase before merging

### CODE REVIEW

**Comment by Ty-Won** [comment]
@ZD1wang build failed

**Comment by ZD1wang** [comment]
> @ZD1wang build failed

fixed!

**Comment by Ty-Won** [comment]
@ZD1wang  theres conflicts :(

**Comment by ZD1wang** [comment]
> @ZD1wang theres conflicts :(

I created a new branch, please check

**Pull request closed without merging**
