### PR TITLE
George redirection

### PR DESCRIPTION
**Pull request by Georges1998**
# Description
This pull request redirect the user to the add food item page after login. 

Fixes # (issue)
Still missing the login to authenticate users. However, the password and email are captured and ready to call a post request. 

## Type of change
Functional requirement. 

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?
TestA:
Integration Testing
TestB:
print(email, password)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I will rebase before merging

### CODE REVIEW

**Comment by TamPhilip** [comment]
Let me know when you push I'll pull your CInput changes

**Comment by Georges1998** [comment]
@yuedai0531 @TamPhilip I tried to rebase but now I'm getting some conflicts. Help?

**Comment by TamPhilip** [comment]
I'm not sure what to say tbh the only thing I could say is maybe squash the commits? @Ty-Won will probably know better!

**Comment by Georges1998** [comment]
This pull request has been revised and fixed https://github.com/hack4impact-mcgill/MealCare/pull/23

**Pull request closed without merging**
