### PR TITLE
Nav change, custom buttons and textfield, widgets page, gesture recognizer

### PR DESCRIPTION
**Pull request by TamPhilip**
# Description

- Created an Abstract Button class to allow others buttons to inherit, with default values.
- Update CustomButton to a CustomFlatButton and CustomRaisedButton class that is customizable 
 with default values (width, height, text style, text, etc) inherits from AbstractButton.
- Updated file names to follow proper dart styling (based off [Effective Dart](https://dart.dev/guides/language/effective-dart/style))
- Updated Navigation to follow named routing (less code duplication based off [flutter docs](https://flutter.dev/docs/cookbook/navigation/named-routes))
- Created a Widgets Page to be able to test widgets (Buttons, TextField).
- Added a Gesture Recognizer in the Login Page to be able to hide keyboard with tap.
- Updated the SingleViewController with a maximum height constraint-based off the max height of the device so the screen is not scrollable.
- Finished Custom Text Field (previously Custom Input) is customizable with default values(width, height, hint text, etc)
- Updated Sidebar such that it can take in a Logout Function.

Fixes # (issue)

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested on 3 different devices iPhone SE, iPhone Pro 11 Max, iPad Pro.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I will rebase before merging

### CODE REVIEW

**Comment by TamPhilip** [comment]
So after a meeting with @Georges1998 we've decided to merge this pr. 

Some things we talked about and agreed on:
- Page Views is needed and will be implemented in george's pr.
- Classes are a safer implementation of widgets, but longer implementation than function widgets. We will proceed with classes.

Some things we would like to talk about in next meeting:
- app state (Storing data)

**Comment by Georges1998** [comment]
looks good to me! But can we still wait until Tuesday anyway to discuss the home page/ login page thing. Also, can you rename the files instead of recreating new files and copying the content of the old files? if you're just updating the name just rename the file instead of creating a new one. The reusable widgets look sick, so if you want create a new pr only for the buttons! 👌🏻

**Comment by TamPhilip** [comment]
@Georges1998 sounds good, I had renamed the files, but I guess it lost track of it while I was fixing my pr.

**Comment by TamPhilip** [comment]
@Georges1998 So the commit for the name changes is required for the history to follow because it wasn't automatically detecting name changes. Let me know if there is anything else to change thanks for the catch

**Comment by TamPhilip** [comment]
@Georges1998 So the commit for the name changes is there for the history to follow because it wasn't automatically detecting name changes, but the files are still being detected as deleted so I think it's not fixable. Good catch though, file changes should be detectable if we want to look back in history now, let me know if I should change anything else 👌

**Comment by Georges1998** [comment]
LGTM!

**Pull request merged**
