### PR TITLE
Feature/philiptam/ui fields food submission

### PR DESCRIPTION
**Pull request by TamPhilip**
# Description

- Created an Abstract Button class to allow others buttons to inherit, with default values.
- Update CustomButton to a CustomFlatButton and CustomRaisedButton class that is customizable 
 with default values (width, height, text style, text, etc) inherits from AbstractButton.
- Updated file names to follow proper dart styling (based off [Effective Dart](https://dart.dev/guides/language/effective-dart/style))
- Updated Navigation to follow named routing (less code duplication based off [flutter docs](https://flutter.dev/docs/cookbook/navigation/named-routes))
- Created a Widgets Page to be able to test widgets (Buttons, TextField).
- Added a Gesture Recognizer in the Login Page to be able to hide keyboard with tap.
- Updated the SingleViewController with a maximum height constraint-based off the max height of the device so the screen is not scrollable.
- Finished Custom Text Field (previously Custom Input) is customizable with default values(width, height, hint text, etc)
- Updated Sidebar such that it can take in a Logout Function.

Fixes # (issue)

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested on 3 different devices iPhone SE, iPhone Pro 11 Max, iPad Pro.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I will rebase before merging

### CODE REVIEW

**Comment by TamPhilip** [comment]
@Georges1998 Pushing and popping can only cause memory issues if you never pop, however in the current context the navigator goes to that route and then pops it, or pushes while replacing which pops the ancestors. #27 I like the idea of using page views for login => location or maybe swiping between the details of vendors, but I think we should be using navigators for the main navigation.

**Comment by Georges1998** [comment]
@TamPhilip ya I agree but having a main entry would make our state management much easier since we won't have to rebuild the current state every time w navigate from page to another. Example: the isAuth boolean in mainPage in my most recent pull request.

**Comment by TamPhilip** [comment]
@Georges1998  When you talk about state management can you clarify it? (From my understanding are you talking about ProfileData, SettingsData, and wanting to keep that data in the page so it doesn't rebuild)

**Comment by Georges1998** [comment]
Sure, so the user was on the profile page, then decided to modify some items in foodItemPage, however, realized that they needed to contact the manager so they pop to the profile and contact the manager. the state of the foodItemPage is now lost. the user has to redo what they were doing before contacting the manager.

**Pull request closed without merging**
