### PR TITLE
Added router, created Login view, some structuring

### PR DESCRIPTION
**Pull request by zzzrg**
# Description

Added router, created Login view, restructured the project. Deleted the boilerplate code.
Added a new dependency "vue-router".

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.  
Provide instructions so we can **reproduce**.  
Please also list any relevant details for your test configuration

- [x] npm run serve

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I will rebase before merging

### CODE REVIEW

**Comment by Ty-Won** [comment]
o my god 23 days holy, im on it

**Comment by Ty-Won** [comment]
@zzzrg When you have time, could you link a screenshot for how it is supposed to appear on your end? Thanks!

**Comment by zzzrg** [comment]
Is it looking different for you?

Screen Shot 2020-05-06 at 10 21 44 AM

**Comment by Ty-Won** [comment]
@zzzrg Nono I just wanted to have a screenshot to refer to so that when I run it, I can compare it to what it is supposed to be :)

**Pull request merged**
